name: android_ci

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: set up Java
      uses: actions/setup-java@v4
      with:
        java-version: '8'
        distribution: 'zulu'

    - name: Get google java format
      run: |
        wget https://github.com/google/google-java-format/releases/download/v1.23.0/google-java-format-1.23.0.jar

    - name: Google Java Format
      uses: axel-op/googlejavaformat-action@v4
      with:
        args: "--set-exit-if-changed"

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Install Nix
      uses: cachix/install-nix-action@v27
      with:
        nix_path: nixpkgs=channel:nixos-unstable

    - name: Build and Test with Nix
      run: |
        nix develop .# -c gradle assembleRelease assembleDebug test --no-daemon

    - name: Upload APKs
      uses: actions/upload-artifact@v4
      with:
        name: nwipe-android-apks
        path: app/build/outputs/apk/**/*.apk
