name: android_ci

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  format-check:
    runs-on: ubuntu-latest
    name: Check Formatting
    steps:
    - uses: actions/checkout@v6

    - name: Install Nix
      uses: cachix/install-nix-action@v30
      with:
        nix_path: nixpkgs=channel:nixos-unstable

    - name: Check Java Formatting
      run: |
        nix develop .# -c sh -c 'google-java-format --dry-run --set-exit-if-changed $(find . -path "*/build" -prune -o -name "*.java" -print)'

  build:
    runs-on: ubuntu-latest
    name: Build the APK
    needs:
      - format-check
    steps:
    - uses: actions/checkout@v6

    - name: Install Nix
      uses: cachix/install-nix-action@v30
      with:
        nix_path: nixpkgs=channel:nixos-unstable

    - name: Build and Test with Nix
      run: |
        nix develop .# -c gradle assembleRelease assembleDebug test --no-daemon

    - name: Upload APKs
      uses: actions/upload-artifact@v6
      with:
        name: nwipe-android-apks
        path: app/build/outputs/apk/**/*.apk
